stack_name: "lab-soc"
tools:
  - plugin: wazuh
    mode: auto-install
    variables:
      admin_password: "MyS3cur3P@ss!"
  - plugin: suricata
    mode: ids
    variables:
      interface: ""   # à adapter selon l'interface réseau du serveur