stack_name: "lab-soc"
tools:
  - plugin: wazuh
    mode: single-node
    variables:
      admin_password: "MyS3cur3P@ss!"
  - plugin: suricata
    mode: ips
    variables:
      interface: ""
      auto_rules: false