stack_name: "lab-soc"
tools:
  - plugin: wazuh
    mode: auto-install
    variables:
      admin_password: "MyS3cur3P@ss!"
  - plugin: suricata
    mode: ids
    variables:
      interface: ""        # laisser vide pour détection auto
      auto_rules: true     # true pour activer les règles automatiquement